/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Main.RouteSystemContext;
import User.UserRole;
import javax.swing.JOptionPane;

/**
 *
 * @author javie
 */
public class CrearCuenta extends javax.swing.JFrame {
    
     private RouteSystemContext context;
    /**
     * Creates new form CrearCuenta
     */
    public CrearCuenta(RouteSystemContext context) {
        this.context = context;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registroLabel = new javax.swing.JLabel();
        nombreUsuarioLabel = new javax.swing.JLabel();
        nombreUsuarioTField = new javax.swing.JTextField();
        correoLabel = new javax.swing.JLabel();
        correoTField = new javax.swing.JTextField();
        contraniaLabel = new javax.swing.JLabel();
        contraseniaPField = new javax.swing.JPasswordField();
        mostrarContraseniaCheckBox = new javax.swing.JCheckBox();
        registrarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CrearCuenta");

        registroLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        registroLabel.setText("Registro");

        nombreUsuarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreUsuarioLabel.setText("Nombre de usario");

        nombreUsuarioTField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        correoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        correoLabel.setText("Correo");

        correoTField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        contraniaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contraniaLabel.setText("Contraseña");

        contraseniaPField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mostrarContraseniaCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrarContraseniaCheckBox.setText("Mostrar constraseña");

        registrarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        registrarButton.setText("Registrar");
        registrarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(registroLabel))
                    .addComponent(mostrarContraseniaCheckBox)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(nombreUsuarioLabel)
                        .addComponent(nombreUsuarioTField)
                        .addComponent(correoLabel)
                        .addComponent(correoTField)
                        .addComponent(contraniaLabel)
                        .addComponent(contraseniaPField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(registrarButton))
                .addContainerGap(252, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(registroLabel)
                .addGap(41, 41, 41)
                .addComponent(nombreUsuarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuarioTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(correoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(correoTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(contraniaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseniaPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mostrarContraseniaCheckBox)
                .addGap(18, 18, 18)
                .addComponent(registrarButton)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registrarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarButtonActionPerformed
        if (context.getAuthenticationService().register(nombreUsuarioTField.getText(), contraseniaPField.getText(), UserRole.USER) != null) {
            this.dispose();
            new MenuUsarioRegular(context).setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "El nombre de usuario ya existe.");
        }
    }//GEN-LAST:event_registrarButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraniaLabel;
    private javax.swing.JPasswordField contraseniaPField;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField correoTField;
    private javax.swing.JCheckBox mostrarContraseniaCheckBox;
    private javax.swing.JLabel nombreUsuarioLabel;
    private javax.swing.JTextField nombreUsuarioTField;
    private javax.swing.JButton registrarButton;
    private javax.swing.JLabel registroLabel;
    // End of variables declaration//GEN-END:variables
}
