/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Admin.StationManagementService;
import Main.RouteSystemContext;
import Vehicle.ChargerType;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author javie
 */
public class EditarCargador extends javax.swing.JFrame {
    
    private RouteSystemContext context;
    private javax.swing.JFrame menuAdmin;
    /**
     * Creates new form EditarCargador
     */
    public EditarCargador(RouteSystemContext context, javax.swing.JFrame menuAdmin) {
        this.context = context;
        this.menuAdmin = menuAdmin;
        initComponents();
    }
    
    /**
     * Carga todos los cargadores en la tabla
     */
    public void cargarCargadores() {
        try {
            StationManagementService servicioManejoEstaciones = context.getAdminService().getStationManager();
            List<ChargerType> cargadores = servicioManejoEstaciones.getAllChargerTypes();
            
            DefaultTableModel tablaContenido = (DefaultTableModel) estacionesTable.getModel();
            tablaContenido.setRowCount(0); // Limpiar tabla
            
            for (ChargerType cargador : cargadores) {
                tablaContenido.addRow(new Object[] {
                    cargador.getName()
                });
            }
            
            // Actualizar el estado del botón eliminar
            actualizarEstadoBotonEliminar();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, 
                "Error al cargar cargadores: " + e.getMessage(), 
                "Error", 
                JOptionPane.ERROR_MESSAGE);
        }
    }
    
    /**
     * Actualiza el estado del botón eliminar según si hay cargadores seleccionados
     */
    private void actualizarEstadoBotonEliminar() {
        int filaSeleccionada = estacionesTable.getSelectedRow();
        eliminarButton.setEnabled(filaSeleccionada >= 0);
    }
    
    private void eliminarUsuarioSeleccionado() {
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        estacionesScrollPane = new javax.swing.JScrollPane();
        estacionesTable = new javax.swing.JTable();
        agregarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();
        listoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        estacionesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Estaciones"
            }
        ));
        estacionesScrollPane.setViewportView(estacionesTable);

        agregarButton.setText("Agregar");

        eliminarButton.setText("Eliminar");

        listoButton.setText("Listo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(estacionesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregarButton)
                    .addComponent(eliminarButton)
                    .addComponent(listoButton))
                .addGap(129, 129, 129))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(agregarButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarButton)
                        .addGap(18, 18, 18)
                        .addComponent(listoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(estacionesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JScrollPane estacionesScrollPane;
    private javax.swing.JTable estacionesTable;
    private javax.swing.JButton listoButton;
    // End of variables declaration//GEN-END:variables
}
