/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Main.RouteSystemContext;
import Services.AuthenticationService;
import javax.swing.JOptionPane;

/**
 *
 * @author javie
 */
public class InicioSesion extends javax.swing.JFrame {
    
    private RouteSystemContext context;
    
    /**
     * Creates new form InicioSesion
     */
    public InicioSesion(RouteSystemContext context) {
        this.context = context;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inicioSesionLabel = new javax.swing.JLabel();
        nombreUsuarioLabel = new javax.swing.JLabel();
        nombreUsuarioTField = new javax.swing.JTextField();
        contraseniaLabel = new javax.swing.JLabel();
        contraseniaPField = new javax.swing.JPasswordField();
        mostrarContraseniaCheckBox = new javax.swing.JCheckBox();
        iniciarButton = new javax.swing.JButton();
        crearCuentaButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inicio de sesión");

        inicioSesionLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        inicioSesionLabel.setText("Incio de sesión");

        nombreUsuarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreUsuarioLabel.setText("Nombre de usuario:");

        nombreUsuarioTField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        contraseniaLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        contraseniaLabel.setText("Contraseña");

        contraseniaPField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        mostrarContraseniaCheckBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        mostrarContraseniaCheckBox.setText("Mostrar constraseña");
        mostrarContraseniaCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarContraseniaCheckBoxActionPerformed(evt);
            }
        });

        iniciarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        iniciarButton.setText("Inciar");
        iniciarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iniciarButtonActionPerformed(evt);
            }
        });

        crearCuentaButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        crearCuentaButton.setText("Crear cuenta");
        crearCuentaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearCuentaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nombreUsuarioLabel)
                            .addComponent(contraseniaLabel)
                            .addComponent(mostrarContraseniaCheckBox)
                            .addComponent(nombreUsuarioTField)
                            .addComponent(contraseniaPField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iniciarButton)
                        .addGap(64, 64, 64)
                        .addComponent(crearCuentaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(inicioSesionLabel)))
                .addContainerGap(226, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(inicioSesionLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40)
                .addComponent(nombreUsuarioLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsuarioTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(contraseniaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contraseniaPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mostrarContraseniaCheckBox)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iniciarButton)
                    .addComponent(crearCuentaButton))
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void iniciarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iniciarButtonActionPerformed
        AuthenticationService controladorAutenticacion = context.getAuthenticationService();
        if (controladorAutenticacion.login(nombreUsuarioTField.getText(), contraseniaPField.getText())) {
            this.dispose();
            if (controladorAutenticacion.getCurrentUser().isAdmin()) {
                MenuAdmin menuAdmin = new MenuAdmin(context);
                menuAdmin.iniciarTablaUsuarios();
                menuAdmin.setVisible(true);
            }
            else {
                MenuUsuarioRegular menuUsuarioRegular = new MenuUsuarioRegular(context);
                menuUsuarioRegular.iniciarTabla();
                menuUsuarioRegular.setVisible(true);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Nombre de usuario o contraseña incorrecta.");
        }
    }//GEN-LAST:event_iniciarButtonActionPerformed

    private void crearCuentaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearCuentaButtonActionPerformed
        this.dispose();
        new CrearCuenta(context).setVisible(true);
    }//GEN-LAST:event_crearCuentaButtonActionPerformed

    private void mostrarContraseniaCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarContraseniaCheckBoxActionPerformed
        
    }//GEN-LAST:event_mostrarContraseniaCheckBoxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel contraseniaLabel;
    private javax.swing.JPasswordField contraseniaPField;
    private javax.swing.JButton crearCuentaButton;
    private javax.swing.JButton iniciarButton;
    private javax.swing.JLabel inicioSesionLabel;
    private javax.swing.JCheckBox mostrarContraseniaCheckBox;
    private javax.swing.JLabel nombreUsuarioLabel;
    private javax.swing.JTextField nombreUsuarioTField;
    // End of variables declaration//GEN-END:variables
}
