/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author javie
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabs = new javax.swing.JTabbedPane();
        usuariosPanel = new javax.swing.JPanel();
        listaUsuariosScrollPane = new javax.swing.JScrollPane();
        listaUsuariosTabla = new javax.swing.JTable();
        nombreUsuarioLabel = new javax.swing.JLabel();
        nombreUsuarioTField = new javax.swing.JTextField();
        correoLabel = new javax.swing.JLabel();
        correoTField = new javax.swing.JTextField();
        agregarUsuarioButton = new javax.swing.JButton();
        eliminarUsuarioButton = new javax.swing.JButton();
        editarButton = new javax.swing.JButton();
        cargarArchivoButton = new javax.swing.JButton();
        mapaPanel = new javax.swing.JPanel();
        nombreCiudadLabel = new javax.swing.JLabel();
        nombreCiudadTField = new javax.swing.JTextField();
        estacionCiudadButton = new javax.swing.JButton();
        agregarCiudadButton = new javax.swing.JButton();
        eliminarCiudadButton = new javax.swing.JButton();
        editarConexionesLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        estacionesPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listaUsuariosTabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Lista de usuarios"
            }
        ));
        listaUsuariosScrollPane.setViewportView(listaUsuariosTabla);

        nombreUsuarioLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreUsuarioLabel.setText("Nombre de usuario:");

        nombreUsuarioTField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        correoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        correoLabel.setText("Correo:");

        correoTField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        agregarUsuarioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarUsuarioButton.setText("Agregar");

        eliminarUsuarioButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminarUsuarioButton.setText("Eliminar");

        editarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editarButton.setText("Editar");

        cargarArchivoButton.setText("Cargar archivo");

        javax.swing.GroupLayout usuariosPanelLayout = new javax.swing.GroupLayout(usuariosPanel);
        usuariosPanel.setLayout(usuariosPanelLayout);
        usuariosPanelLayout.setHorizontalGroup(
            usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listaUsuariosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(nombreUsuarioLabel)
                                .addComponent(nombreUsuarioTField, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(correoLabel)
                                .addComponent(correoTField))
                            .addComponent(eliminarUsuarioButton)
                            .addComponent(editarButton)
                            .addComponent(agregarUsuarioButton)))
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(cargarArchivoButton)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        usuariosPanelLayout.setVerticalGroup(
            usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(usuariosPanelLayout.createSequentialGroup()
                .addGroup(usuariosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(nombreUsuarioLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreUsuarioTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(correoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(correoTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(agregarUsuarioButton)
                        .addGap(18, 18, 18)
                        .addComponent(editarButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarUsuarioButton))
                    .addGroup(usuariosPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(listaUsuariosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(cargarArchivoButton)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tabs.addTab("Usuarios", usuariosPanel);

        nombreCiudadLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreCiudadLabel.setText("Nombre de ciudad:");

        nombreCiudadTField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        estacionCiudadButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        estacionCiudadButton.setText("Estación en ciudad");

        agregarCiudadButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarCiudadButton.setText("Agregar");

        eliminarCiudadButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminarCiudadButton.setText("Eliminar");

        editarConexionesLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        editarConexionesLabel.setText("Editar conexiones:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout mapaPanelLayout = new javax.swing.GroupLayout(mapaPanel);
        mapaPanel.setLayout(mapaPanelLayout);
        mapaPanelLayout.setHorizontalGroup(
            mapaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mapaPanelLayout.createSequentialGroup()
                .addContainerGap(362, Short.MAX_VALUE)
                .addGroup(mapaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mapaPanelLayout.createSequentialGroup()
                        .addComponent(agregarCiudadButton)
                        .addGap(18, 18, 18)
                        .addComponent(eliminarCiudadButton))
                    .addComponent(estacionCiudadButton)
                    .addComponent(nombreCiudadLabel)
                    .addComponent(nombreCiudadTField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarConexionesLabel))
                .addGap(138, 138, 138))
        );
        mapaPanelLayout.setVerticalGroup(
            mapaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mapaPanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(nombreCiudadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreCiudadTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(estacionCiudadButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(mapaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agregarCiudadButton)
                    .addComponent(eliminarCiudadButton))
                .addGap(30, 30, 30)
                .addComponent(editarConexionesLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        tabs.addTab("Mapa", mapaPanel);

        javax.swing.GroupLayout estacionesPanelLayout = new javax.swing.GroupLayout(estacionesPanel);
        estacionesPanel.setLayout(estacionesPanelLayout);
        estacionesPanelLayout.setHorizontalGroup(
            estacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        estacionesPanelLayout.setVerticalGroup(
            estacionesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 465, Short.MAX_VALUE)
        );

        tabs.addTab("Estaciones", estacionesPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabs)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarCiudadButton;
    private javax.swing.JButton agregarUsuarioButton;
    private javax.swing.JButton cargarArchivoButton;
    private javax.swing.JLabel correoLabel;
    private javax.swing.JTextField correoTField;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel editarConexionesLabel;
    private javax.swing.JButton eliminarCiudadButton;
    private javax.swing.JButton eliminarUsuarioButton;
    private javax.swing.JButton estacionCiudadButton;
    private javax.swing.JPanel estacionesPanel;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JScrollPane listaUsuariosScrollPane;
    private javax.swing.JTable listaUsuariosTabla;
    private javax.swing.JPanel mapaPanel;
    private javax.swing.JLabel nombreCiudadLabel;
    private javax.swing.JTextField nombreCiudadTField;
    private javax.swing.JLabel nombreUsuarioLabel;
    private javax.swing.JTextField nombreUsuarioTField;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JPanel usuariosPanel;
    // End of variables declaration//GEN-END:variables
}
