/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author javie
 */
public class MenuUsarioRegular extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuarioRegular
     */
    public MenuUsarioRegular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane4 = new javax.swing.JTabbedPane();
        rutasPanel = new javax.swing.JPanel();
        origenLabel = new javax.swing.JLabel();
        origenCBox = new javax.swing.JComboBox<>();
        destinoLabel = new javax.swing.JLabel();
        destinoCBox = new javax.swing.JComboBox<>();
        filtrarLabel = new javax.swing.JLabel();
        porVehiculoRButton = new javax.swing.JRadioButton();
        porTipoRButton = new javax.swing.JRadioButton();
        filtrarCBox = new javax.swing.JComboBox<>();
        tablaScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        vehiculosPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        nombreLabel = new javax.swing.JLabel();
        nombreTField = new javax.swing.JTextField();
        tipoVehiculoLabel = new javax.swing.JLabel();
        electricoRButton = new javax.swing.JRadioButton();
        combustibleRButton = new javax.swing.JRadioButton();
        tipoCombustibleLabel = new javax.swing.JLabel();
        tipoCombustibleCBox = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");

        origenLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        origenLabel.setText("Orígen:");

        origenCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        origenCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        destinoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        destinoLabel.setText("Destino:");

        destinoCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        destinoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filtrarLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filtrarLabel.setText("Filtrar:");

        porVehiculoRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        porVehiculoRButton.setText("Por vehículo");

        porTipoRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        porTipoRButton.setText("Por tipo");

        filtrarCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filtrarCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaScrollPane1.setViewportView(tabla);

        javax.swing.GroupLayout rutasPanelLayout = new javax.swing.GroupLayout(rutasPanel);
        rutasPanel.setLayout(rutasPanelLayout);
        rutasPanelLayout.setHorizontalGroup(
            rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutasPanelLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filtrarCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(filtrarLabel)
                        .addGroup(rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(origenLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(destinoLabel)))
                    .addComponent(origenCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(destinoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(porVehiculoRButton)
                    .addComponent(porTipoRButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(tablaScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        rutasPanelLayout.setVerticalGroup(
            rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutasPanelLayout.createSequentialGroup()
                .addGroup(rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rutasPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(origenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(origenCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(destinoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(filtrarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porVehiculoRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porTipoRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filtrarCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rutasPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tablaScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Rutas", rutasPanel);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreLabel.setText("Nombre:");

        tipoVehiculoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoVehiculoLabel.setText("Tipo de vehículo:");

        electricoRButton.setText("Eléctrico");

        combustibleRButton.setText("Combustible");

        tipoCombustibleLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoCombustibleLabel.setText("Tipo de combustible:");

        tipoCombustibleCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout vehiculosPanelLayout = new javax.swing.GroupLayout(vehiculosPanel);
        vehiculosPanel.setLayout(vehiculosPanelLayout);
        vehiculosPanelLayout.setHorizontalGroup(
            vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculosPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98)
                .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiculosPanelLayout.createSequentialGroup()
                        .addComponent(electricoRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combustibleRButton, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(95, Short.MAX_VALUE))
                    .addGroup(vehiculosPanelLayout.createSequentialGroup()
                        .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreLabel)
                            .addComponent(nombreTField, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tipoVehiculoLabel)
                            .addComponent(tipoCombustibleLabel)
                            .addComponent(tipoCombustibleCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        vehiculosPanelLayout.setVerticalGroup(
            vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculosPanelLayout.createSequentialGroup()
                .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(vehiculosPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(vehiculosPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tipoVehiculoLabel)
                        .addGap(18, 18, 18)
                        .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(electricoRButton)
                            .addComponent(combustibleRButton))
                        .addGap(31, 31, 31)
                        .addComponent(tipoCombustibleLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoCombustibleCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Vehículos", vehiculosPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsarioRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsarioRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsarioRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsarioRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsarioRegular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton combustibleRButton;
    private javax.swing.JComboBox<String> destinoCBox;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JRadioButton electricoRButton;
    private javax.swing.JComboBox<String> filtrarCBox;
    private javax.swing.JLabel filtrarLabel;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTField;
    private javax.swing.JComboBox<String> origenCBox;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JRadioButton porTipoRButton;
    private javax.swing.JRadioButton porVehiculoRButton;
    private javax.swing.JPanel rutasPanel;
    private javax.swing.JTable tabla;
    private javax.swing.JScrollPane tablaScrollPane1;
    private javax.swing.JComboBox<String> tipoCombustibleCBox;
    private javax.swing.JLabel tipoCombustibleLabel;
    private javax.swing.JLabel tipoVehiculoLabel;
    private javax.swing.JPanel vehiculosPanel;
    // End of variables declaration//GEN-END:variables
}
