
package vista;

import Main.RouteSystemContext;
import Services.VehicleService;
import User.UserService;
import Vehicle.ElectricVehicle;
import Vehicle.FuelVehicle;
import Vehicle.Vehicle;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

public class MenuUsuarioRegular extends javax.swing.JFrame {
    
    private RouteSystemContext context;
    
    /**
     * Creates new form MenuUsuarioRegular
     */
    public MenuUsuarioRegular(RouteSystemContext context) {
        this.context = context;
        initComponents();
    }
    
    public void iniciarTabla() {
        UserService servicioUsuario = context.getUserService();
        List<Vehicle> vehiculos = servicioUsuario.getVehicleService().getCurrentUserVehicles();
        DefaultTableModel tablaContenido = (DefaultTableModel) tablaVehiculos.getModel();
        for (Vehicle v : vehiculos) {
            tablaContenido.addRow(new Object[] {v.getMake(), v.getEnergyType(), true});
        }
        tablaVehiculos.setModel(tablaContenido);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtroBGroup = new javax.swing.ButtonGroup();
        tipoVehiculoBGroup = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        rutasPanel = new javax.swing.JPanel();
        tablaRutasScrollPane = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        origenLabel = new javax.swing.JLabel();
        origenCBox = new javax.swing.JComboBox<>();
        destinoLabel = new javax.swing.JLabel();
        destinoCBox = new javax.swing.JComboBox<>();
        filtrarLabel = new javax.swing.JLabel();
        porVehiculoRButton = new javax.swing.JRadioButton();
        porTipoRButton = new javax.swing.JRadioButton();
        filtrarCBox = new javax.swing.JComboBox<>();
        vehiculosPanel = new javax.swing.JPanel();
        tablaVehiculosScrollPane = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        nombreLabel = new javax.swing.JLabel();
        nombreTField = new javax.swing.JTextField();
        tipoVehiculoLabel = new javax.swing.JLabel();
        electricoRButton = new javax.swing.JRadioButton();
        combustibleRButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        tipoCombustibleCbox = new javax.swing.JComboBox<>();
        agregarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");

        rutasPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Orígen", "Destino"
            }
        ));
        tablaRutasScrollPane.setViewportView(tablaRutas);

        rutasPanel.add(tablaRutasScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        origenLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        origenLabel.setText("Orígen:");
        rutasPanel.add(origenLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 50, -1, -1));

        origenCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        origenCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rutasPanel.add(origenCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 80, -1, -1));

        destinoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        destinoLabel.setText("Destino:");
        rutasPanel.add(destinoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 120, -1, -1));

        destinoCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        destinoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rutasPanel.add(destinoCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        filtrarLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filtrarLabel.setText("Filtrar:");
        rutasPanel.add(filtrarLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 190, -1, -1));

        filtroBGroup.add(porVehiculoRButton);
        porVehiculoRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        porVehiculoRButton.setSelected(true);
        porVehiculoRButton.setText("Por vehículo");
        rutasPanel.add(porVehiculoRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, -1, -1));

        filtroBGroup.add(porTipoRButton);
        porTipoRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        porTipoRButton.setText("Por tipo");
        rutasPanel.add(porTipoRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, -1, -1));

        filtrarCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filtrarCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rutasPanel.add(filtrarCBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 280, -1, -1));

        jTabbedPane4.addTab("Rutas", rutasPanel);

        vehiculosPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Vehículos", "Tipo", "Favorito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaVehiculosScrollPane.setViewportView(tablaVehiculos);

        vehiculosPanel.add(tablaVehiculosScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 12, 430, 420));

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreLabel.setText("Nombre:");
        vehiculosPanel.add(nombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));
        vehiculosPanel.add(nombreTField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, -1, -1));

        tipoVehiculoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoVehiculoLabel.setText("Tipo de vehículo:");
        vehiculosPanel.add(tipoVehiculoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, -1, -1));

        tipoVehiculoBGroup.add(electricoRButton);
        electricoRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        electricoRButton.setText("Eléctrico");
        vehiculosPanel.add(electricoRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, -1, -1));

        tipoVehiculoBGroup.add(combustibleRButton);
        combustibleRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combustibleRButton.setSelected(true);
        combustibleRButton.setText("Combustible");
        vehiculosPanel.add(combustibleRButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 120, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de combustible:");
        vehiculosPanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 160, -1, -1));

        tipoCombustibleCbox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoCombustibleCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        vehiculosPanel.add(tipoCombustibleCbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 190, -1, -1));

        agregarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarButton.setText("Agregar");
        agregarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarButtonActionPerformed(evt);
            }
        });
        vehiculosPanel.add(agregarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        eliminarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });
        vehiculosPanel.add(eliminarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 250, -1, -1));

        jTabbedPane4.addTab("Vehículos", vehiculosPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarButtonActionPerformed
        VehicleService servicioVehiculos = context.getUserService().getVehicleService();
        DefaultTableModel tablaContenido = (DefaultTableModel) tablaVehiculos.getModel();
        Vehicle nuevoVehiculo;
        if (electricoRButton.isSelected()) {
            nuevoVehiculo = new ElectricVehicle(nombreTField.getText(), "0", 1900, "0", new ArrayList<>(), 0.0D);
            tablaContenido.addRow(new Object[] {nombreTField.getText(), "Elétrico", true});
        }
        else {
            nuevoVehiculo = new FuelVehicle(nombreTField.getText(), "0", 1900, "0", null, 0.0D);
            tablaContenido.addRow(new Object[] {nombreTField.getText(), "Gasolina", true});
        }
        servicioVehiculos.addVehicle(nuevoVehiculo);
        tablaVehiculos.setModel(tablaContenido);
    }//GEN-LAST:event_agregarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        VehicleService servicioVehiculos = context.getUserService().getVehicleService();
        DefaultTableModel tablaContenido = (DefaultTableModel) tablaVehiculos.getModel();
        List<Vehicle> vehiculos = servicioVehiculos.getCurrentUserVehicles();
        int filaSeleccionada = tablaVehiculos.getSelectedRow();
        if (filaSeleccionada != -1) {
            Vehicle vehiculoRemover = vehiculos.get(filaSeleccionada);
            servicioVehiculos.removeVehicle(vehiculoRemover);
            tablaContenido.removeRow(filaSeleccionada);
            tablaVehiculos.setModel(tablaContenido);
        } 
    }//GEN-LAST:event_eliminarButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JRadioButton combustibleRButton;
    private javax.swing.JComboBox<String> destinoCBox;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JRadioButton electricoRButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JComboBox<String> filtrarCBox;
    private javax.swing.JLabel filtrarLabel;
    private javax.swing.ButtonGroup filtroBGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTField;
    private javax.swing.JComboBox<String> origenCBox;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JRadioButton porTipoRButton;
    private javax.swing.JRadioButton porVehiculoRButton;
    private javax.swing.JPanel rutasPanel;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JScrollPane tablaRutasScrollPane;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JScrollPane tablaVehiculosScrollPane;
    private javax.swing.JComboBox<String> tipoCombustibleCbox;
    private javax.swing.ButtonGroup tipoVehiculoBGroup;
    private javax.swing.JLabel tipoVehiculoLabel;
    private javax.swing.JPanel vehiculosPanel;
    // End of variables declaration//GEN-END:variables
}
