/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author javie
 */
public class MenuUsarioRegular extends javax.swing.JFrame {

    /**
     * Creates new form MenuUsuarioRegular
     */
    public MenuUsarioRegular() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filtroBGroup = new javax.swing.ButtonGroup();
        tipoVehiculoBGroup = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jTabbedPane4 = new javax.swing.JTabbedPane();
        rutasPanel = new javax.swing.JPanel();
        tablaRutasScrollPane = new javax.swing.JScrollPane();
        tablaRutas = new javax.swing.JTable();
        origenLabel = new javax.swing.JLabel();
        origenCBox = new javax.swing.JComboBox<>();
        destinoLabel = new javax.swing.JLabel();
        destinoCBox = new javax.swing.JComboBox<>();
        filtrarLabel = new javax.swing.JLabel();
        porVehiculoRButton = new javax.swing.JRadioButton();
        porTipoRButton = new javax.swing.JRadioButton();
        filtrarCBox = new javax.swing.JComboBox<>();
        vehiculosPanel = new javax.swing.JPanel();
        tablaVehiculosScrollPane = new javax.swing.JScrollPane();
        tablaVehiculos = new javax.swing.JTable();
        nombreLabel = new javax.swing.JLabel();
        nombreTField = new javax.swing.JTextField();
        tipoVehiculoLabel = new javax.swing.JLabel();
        electricoRButton = new javax.swing.JRadioButton();
        combustibleRButton = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        tipoCombustibleCbox = new javax.swing.JComboBox<>();
        agregarButton = new javax.swing.JButton();
        eliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menú");

        tablaRutas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaRutasScrollPane.setViewportView(tablaRutas);

        origenLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        origenLabel.setText("Orígen:");

        origenCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        origenCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        destinoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        destinoLabel.setText("Destino:");

        destinoCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        destinoCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        filtrarLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filtrarLabel.setText("Filtrar:");

        filtroBGroup.add(porVehiculoRButton);
        porVehiculoRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        porVehiculoRButton.setSelected(true);
        porVehiculoRButton.setText("Por vehículo");

        filtroBGroup.add(porTipoRButton);
        porTipoRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        porTipoRButton.setText("Por tipo");

        filtrarCBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        filtrarCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout rutasPanelLayout = new javax.swing.GroupLayout(rutasPanel);
        rutasPanel.setLayout(rutasPanelLayout);
        rutasPanelLayout.setHorizontalGroup(
            rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutasPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(destinoLabel)
                    .addGroup(rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(origenCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(destinoCBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filtrarCBox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(origenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(filtrarLabel)
                    .addComponent(porVehiculoRButton)
                    .addComponent(porTipoRButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(tablaRutasScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );
        rutasPanelLayout.setVerticalGroup(
            rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rutasPanelLayout.createSequentialGroup()
                .addGroup(rutasPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(rutasPanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(origenLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(origenCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(destinoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(destinoCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(filtrarLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porVehiculoRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(porTipoRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(filtrarCBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(rutasPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tablaRutasScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Rutas", rutasPanel);

        tablaVehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Vehiculo1", "Tipo1",  new Boolean(false)}
            },
            new String [] {
                "Vehículos", "Tipo", "Favorito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tablaVehiculosScrollPane.setViewportView(tablaVehiculos);

        nombreLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        nombreLabel.setText("Nombre:");

        tipoVehiculoLabel.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoVehiculoLabel.setText("Tipo de vehículo:");

        tipoVehiculoBGroup.add(electricoRButton);
        electricoRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        electricoRButton.setText("Eléctrico");

        tipoVehiculoBGroup.add(combustibleRButton);
        combustibleRButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        combustibleRButton.setSelected(true);
        combustibleRButton.setText("Combustible");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Tipo de combustible:");

        tipoCombustibleCbox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tipoCombustibleCbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        agregarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        agregarButton.setText("Agregar");

        eliminarButton.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        eliminarButton.setText("Eliminar");

        javax.swing.GroupLayout vehiculosPanelLayout = new javax.swing.GroupLayout(vehiculosPanel);
        vehiculosPanel.setLayout(vehiculosPanelLayout);
        vehiculosPanelLayout.setHorizontalGroup(
            vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculosPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(tablaVehiculosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, vehiculosPanelLayout.createSequentialGroup()
                        .addComponent(electricoRButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combustibleRButton)
                        .addGap(67, 67, 67))
                    .addGroup(vehiculosPanelLayout.createSequentialGroup()
                        .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTField, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nombreLabel)
                            .addComponent(tipoVehiculoLabel)
                            .addComponent(jLabel1)
                            .addComponent(tipoCombustibleCbox, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(vehiculosPanelLayout.createSequentialGroup()
                                .addComponent(agregarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(eliminarButton)))
                        .addContainerGap())))
        );
        vehiculosPanelLayout.setVerticalGroup(
            vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(vehiculosPanelLayout.createSequentialGroup()
                .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(vehiculosPanelLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(nombreLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nombreTField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tipoVehiculoLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(combustibleRButton, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(electricoRButton, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipoCombustibleCbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(vehiculosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(agregarButton)
                            .addComponent(eliminarButton))
                        .addGap(163, 163, 163))
                    .addGroup(vehiculosPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(tablaVehiculosScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane4.addTab("Vehículos", vehiculosPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUsarioRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUsarioRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUsarioRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUsarioRegular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuUsarioRegular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarButton;
    private javax.swing.JRadioButton combustibleRButton;
    private javax.swing.JComboBox<String> destinoCBox;
    private javax.swing.JLabel destinoLabel;
    private javax.swing.JRadioButton electricoRButton;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JComboBox<String> filtrarCBox;
    private javax.swing.JLabel filtrarLabel;
    private javax.swing.ButtonGroup filtroBGroup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane4;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JTextField nombreTField;
    private javax.swing.JComboBox<String> origenCBox;
    private javax.swing.JLabel origenLabel;
    private javax.swing.JRadioButton porTipoRButton;
    private javax.swing.JRadioButton porVehiculoRButton;
    private javax.swing.JPanel rutasPanel;
    private javax.swing.JTable tablaRutas;
    private javax.swing.JScrollPane tablaRutasScrollPane;
    private javax.swing.JTable tablaVehiculos;
    private javax.swing.JScrollPane tablaVehiculosScrollPane;
    private javax.swing.JComboBox<String> tipoCombustibleCbox;
    private javax.swing.ButtonGroup tipoVehiculoBGroup;
    private javax.swing.JLabel tipoVehiculoLabel;
    private javax.swing.JPanel vehiculosPanel;
    // End of variables declaration//GEN-END:variables
}
