/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import Main.RouteSystemContext;

/**
 *
 * @author javie
 */
public class SeleccionarCargador extends javax.swing.JFrame {
    
    private RouteSystemContext context;
    /**
     * Creates new form SeleccionarCargador
     */
    public SeleccionarCargador(RouteSystemContext context) {
        this.context = context;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargadoresScrollPane = new javax.swing.JScrollPane();
        cargadoresTable = new javax.swing.JTable();
        editarButton = new javax.swing.JButton();
        listoButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                SeleccionarCargador.this.windowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                SeleccionarCargador.this.windowClosing(evt);
            }
            public void windowDeactivated(java.awt.event.WindowEvent evt) {
                SeleccionarCargador.this.windowDeactivated(evt);
            }
        });

        cargadoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de cargador", "Está"
            }
        ));
        cargadoresScrollPane.setViewportView(cargadoresTable);

        getContentPane().add(cargadoresScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 650, 290));

        editarButton.setText("Editar tipos de cargador");

        listoButton.setText("Listo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(cargadoresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(editarButton)
                        .addGap(51, 51, 51)
                        .addComponent(listoButton)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(cargadoresScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editarButton)
                    .addComponent(listoButton))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jButton1.setText("Listo");
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 420, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void windowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosing
        MenuAdmin menuAdmin = new MenuAdmin(context);
        menuAdmin.setVisible(true);
    }//GEN-LAST:event_windowClosing

    private void windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosed
        
    }//GEN-LAST:event_windowClosed

    private void windowDeactivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowDeactivated
        
    }//GEN-LAST:event_windowDeactivated

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane cargadoresScrollPane;
    private javax.swing.JTable cargadoresTable;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton listoButton;
    // End of variables declaration//GEN-END:variables
}
