/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

/**
 *
 * @author javie
 */
public class SeleccionarCargador extends javax.swing.JFrame {

    /**
     * Creates new form SeleccionarCargador
     */
    public SeleccionarCargador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cargadoresScrollPane = new javax.swing.JScrollPane();
        cargadoresTable = new javax.swing.JTable();
        editarButton = new javax.swing.JButton();
        listoButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cargadoresTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo de cargador", "Está"
            }
        ));
        cargadoresScrollPane.setViewportView(cargadoresTable);

        getContentPane().add(cargadoresScrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 640, 356));

        editarButton.setText("Editar tipos de cargador");
        getContentPane().add(editarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 430, -1, -1));

        listoButton.setText("Listo");
        getContentPane().add(listoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 430, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane cargadoresScrollPane;
    private javax.swing.JTable cargadoresTable;
    private javax.swing.JButton editarButton;
    private javax.swing.JButton listoButton;
    // End of variables declaration//GEN-END:variables
}
